[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
temp_project = "ACmnALsktmX88En74HFZYFZktw2yZoGrKs9tfQyG9DgS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
